[1m[31mERROR   [0m pika.adapters.utils.selector_ioloop_adapter:selector_ioloop_adapter.py:569 Address resolution failed: gaierror(11001, 'getaddrinfo failed')
[1m[31mERROR   [0m pika.adapters.utils.connection_workflow:connection_workflow.py:799 getaddrinfo failed: gaierror(11001, 'getaddrinfo failed').
[1m[31mERROR   [0m pika.adapters.utils.connection_workflow:connection_workflow.py:746 AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(11001, 'getaddrinfo failed'); first exception - None.
[1m[31mERROR   [0m pika.adapters.utils.connection_workflow:connection_workflow.py:723 AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(11001, 'getaddrinfo failed'); first exception - None
[1m[31mERROR   [0m pika.adapters.blocking_connection:blocking_connection.py:450 Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(11001, 'getaddrinfo failed'); first exception - None
[1m[31mERROR   [0m pika.adapters.blocking_connection:blocking_connection.py:457 Error in _create_connection().
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pika\adapters\blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pika\adapters\utils\selector_ioloop_adapter.py", line 565, in _resolve
    result = socket.getaddrinfo(self._host, self._port, self._family,
                                self._socktype, self._proto,
                                self._flags)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 977, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed